# Generated by Django 3.2.7 on 2021-10-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
